# 修改application.yaml
server:
  port: 5555

shiro:
  # 全局限速器 (基于令牌桶算法)，无需该配置字段可删除，将使用默认值（默认禁用）
  limiter:
    enable: false
    permits-per-second: 1
  # Webscoket连接地址，无需该配置字段可删除，将使用默认值 "/ws/shiro"
  ws-config:
    ws-url: "/ws/valbot"
  # 插件列表 (顺序执行，如果前一个插件返回了MESSAGE_BLOCK，将不会执行后续插件)
  plugin-list:
    - com.ericlam.qqbot.valbot.filter.ValGroupFilter
    - com.ericlam.qqbot.valbot.filter.ChatCommandFilter
    - com.ericlam.qqbot.valbot.filter.ChatResponseFilter